// Generated by gencpp from file exercise1/AddTwoInts.msg
// DO NOT EDIT!


#ifndef EXERCISE1_MESSAGE_ADDTWOINTS_H
#define EXERCISE1_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <exercise1/AddTwoIntsRequest.h>
#include <exercise1/AddTwoIntsResponse.h>


namespace exercise1
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace exercise1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exercise1::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::exercise1::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::exercise1::AddTwoInts > {
  static const char* value()
  {
    return "exercise1/AddTwoInts";
  }

  static const char* value(const ::exercise1::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::exercise1::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::exercise1::AddTwoInts > 
template<>
struct MD5Sum< ::exercise1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exercise1::AddTwoInts >::value();
  }
  static const char* value(const ::exercise1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise1::AddTwoIntsRequest> should match 
// service_traits::DataType< ::exercise1::AddTwoInts > 
template<>
struct DataType< ::exercise1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::exercise1::AddTwoInts >::value();
  }
  static const char* value(const ::exercise1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exercise1::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::exercise1::AddTwoInts > 
template<>
struct MD5Sum< ::exercise1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exercise1::AddTwoInts >::value();
  }
  static const char* value(const ::exercise1::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise1::AddTwoIntsResponse> should match 
// service_traits::DataType< ::exercise1::AddTwoInts > 
template<>
struct DataType< ::exercise1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::exercise1::AddTwoInts >::value();
  }
  static const char* value(const ::exercise1::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXERCISE1_MESSAGE_ADDTWOINTS_H
