(cl:defpackage exercise1-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "REVERSE"
   "<REVERSE-REQUEST>"
   "REVERSE-REQUEST"
   "<REVERSE-RESPONSE>"
   "REVERSE-RESPONSE"
  ))

