// Generated by gencpp from file exercise4/turtle_pos.msg
// DO NOT EDIT!


#ifndef EXERCISE4_MESSAGE_TURTLE_POS_H
#define EXERCISE4_MESSAGE_TURTLE_POS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exercise4
{
template <class ContainerAllocator>
struct turtle_pos_
{
  typedef turtle_pos_<ContainerAllocator> Type;

  turtle_pos_()
    : x(0)
    , y(0)
    , w(0)  {
    }
  turtle_pos_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , w(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef int64_t _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::exercise4::turtle_pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise4::turtle_pos_<ContainerAllocator> const> ConstPtr;

}; // struct turtle_pos_

typedef ::exercise4::turtle_pos_<std::allocator<void> > turtle_pos;

typedef boost::shared_ptr< ::exercise4::turtle_pos > turtle_posPtr;
typedef boost::shared_ptr< ::exercise4::turtle_pos const> turtle_posConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise4::turtle_pos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise4::turtle_pos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exercise4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'exercise4': ['/home/avrelij/Documents/RINS/catkin_ws/src/exercise4/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exercise4::turtle_pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise4::turtle_pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise4::turtle_pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise4::turtle_pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise4::turtle_pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise4::turtle_pos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise4::turtle_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d1044e64b13e39b28976cda53df095d";
  }

  static const char* value(const ::exercise4::turtle_pos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d1044e64b13e39bULL;
  static const uint64_t static_value2 = 0x28976cda53df095dULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise4::turtle_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise4/turtle_pos";
  }

  static const char* value(const ::exercise4::turtle_pos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise4::turtle_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n\
int64 y\n\
int64 w\n\
";
  }

  static const char* value(const ::exercise4::turtle_pos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise4::turtle_pos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turtle_pos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise4::turtle_pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercise4::turtle_pos_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "w: ";
    Printer<int64_t>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE4_MESSAGE_TURTLE_POS_H
