// Generated by gencpp from file vaja01/ArrayOfIntsResponse.msg
// DO NOT EDIT!


#ifndef VAJA01_MESSAGE_ARRAYOFINTSRESPONSE_H
#define VAJA01_MESSAGE_ARRAYOFINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vaja01
{
template <class ContainerAllocator>
struct ArrayOfIntsResponse_
{
  typedef ArrayOfIntsResponse_<ContainerAllocator> Type;

  ArrayOfIntsResponse_()
    : vsota(0)  {
    }
  ArrayOfIntsResponse_(const ContainerAllocator& _alloc)
    : vsota(0)  {
  (void)_alloc;
    }



   typedef int64_t _vsota_type;
  _vsota_type vsota;





  typedef boost::shared_ptr< ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ArrayOfIntsResponse_

typedef ::vaja01::ArrayOfIntsResponse_<std::allocator<void> > ArrayOfIntsResponse;

typedef boost::shared_ptr< ::vaja01::ArrayOfIntsResponse > ArrayOfIntsResponsePtr;
typedef boost::shared_ptr< ::vaja01::ArrayOfIntsResponse const> ArrayOfIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vaja01

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'vaja01': ['/home/avrelij/Documents/RINS/catkin_ws/src/vaja01/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4d569a3f1f3567641c947c9808321aa";
  }

  static const char* value(const ::vaja01::ArrayOfIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4d569a3f1f35676ULL;
  static const uint64_t static_value2 = 0x41c947c9808321aaULL;
};

template<class ContainerAllocator>
struct DataType< ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vaja01/ArrayOfIntsResponse";
  }

  static const char* value(const ::vaja01::ArrayOfIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 vsota\n\
";
  }

  static const char* value(const ::vaja01::ArrayOfIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vsota);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArrayOfIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vaja01::ArrayOfIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vaja01::ArrayOfIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "vsota: ";
    Printer<int64_t>::stream(s, indent + "  ", v.vsota);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VAJA01_MESSAGE_ARRAYOFINTSRESPONSE_H
