// Generated by gencpp from file vaja01/string_ID.msg
// DO NOT EDIT!


#ifndef VAJA01_MESSAGE_STRING_ID_H
#define VAJA01_MESSAGE_STRING_ID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vaja01
{
template <class ContainerAllocator>
struct string_ID_
{
  typedef string_ID_<ContainerAllocator> Type;

  string_ID_()
    : content()
    , seqID(0)  {
    }
  string_ID_(const ContainerAllocator& _alloc)
    : content(_alloc)
    , seqID(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _content_type;
  _content_type content;

   typedef int32_t _seqID_type;
  _seqID_type seqID;





  typedef boost::shared_ptr< ::vaja01::string_ID_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vaja01::string_ID_<ContainerAllocator> const> ConstPtr;

}; // struct string_ID_

typedef ::vaja01::string_ID_<std::allocator<void> > string_ID;

typedef boost::shared_ptr< ::vaja01::string_ID > string_IDPtr;
typedef boost::shared_ptr< ::vaja01::string_ID const> string_IDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vaja01::string_ID_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vaja01::string_ID_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vaja01

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'vaja01': ['/home/avrelij/Documents/RINS/catkin_ws/src/vaja01/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vaja01::string_ID_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vaja01::string_ID_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaja01::string_ID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaja01::string_ID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaja01::string_ID_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaja01::string_ID_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vaja01::string_ID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b57dc76242a9a2500d39577844d88d65";
  }

  static const char* value(const ::vaja01::string_ID_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb57dc76242a9a250ULL;
  static const uint64_t static_value2 = 0x0d39577844d88d65ULL;
};

template<class ContainerAllocator>
struct DataType< ::vaja01::string_ID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vaja01/string_ID";
  }

  static const char* value(const ::vaja01::string_ID_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vaja01::string_ID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string content\n\
int32 seqID\n\
";
  }

  static const char* value(const ::vaja01::string_ID_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vaja01::string_ID_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.content);
      stream.next(m.seqID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct string_ID_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vaja01::string_ID_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vaja01::string_ID_<ContainerAllocator>& v)
  {
    s << indent << "content: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.content);
    s << indent << "seqID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.seqID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VAJA01_MESSAGE_STRING_ID_H
