// Generated by gencpp from file vaja02/Movement.msg
// DO NOT EDIT!


#ifndef VAJA02_MESSAGE_MOVEMENT_H
#define VAJA02_MESSAGE_MOVEMENT_H

#include <ros/service_traits.h>


#include <vaja02/MovementRequest.h>
#include <vaja02/MovementResponse.h>


namespace vaja02
{

struct Movement
{

typedef MovementRequest Request;
typedef MovementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Movement
} // namespace vaja02


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vaja02::Movement > {
  static const char* value()
  {
    return "03ddf760f94194b459db8b360beaa75c";
  }

  static const char* value(const ::vaja02::Movement&) { return value(); }
};

template<>
struct DataType< ::vaja02::Movement > {
  static const char* value()
  {
    return "vaja02/Movement";
  }

  static const char* value(const ::vaja02::Movement&) { return value(); }
};


// service_traits::MD5Sum< ::vaja02::MovementRequest> should match 
// service_traits::MD5Sum< ::vaja02::Movement > 
template<>
struct MD5Sum< ::vaja02::MovementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vaja02::Movement >::value();
  }
  static const char* value(const ::vaja02::MovementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vaja02::MovementRequest> should match 
// service_traits::DataType< ::vaja02::Movement > 
template<>
struct DataType< ::vaja02::MovementRequest>
{
  static const char* value()
  {
    return DataType< ::vaja02::Movement >::value();
  }
  static const char* value(const ::vaja02::MovementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vaja02::MovementResponse> should match 
// service_traits::MD5Sum< ::vaja02::Movement > 
template<>
struct MD5Sum< ::vaja02::MovementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vaja02::Movement >::value();
  }
  static const char* value(const ::vaja02::MovementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vaja02::MovementResponse> should match 
// service_traits::DataType< ::vaja02::Movement > 
template<>
struct DataType< ::vaja02::MovementResponse>
{
  static const char* value()
  {
    return DataType< ::vaja02::Movement >::value();
  }
  static const char* value(const ::vaja02::MovementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VAJA02_MESSAGE_MOVEMENT_H
