// Generated by gencpp from file vaja02/MovementRequest.msg
// DO NOT EDIT!


#ifndef VAJA02_MESSAGE_MOVEMENTREQUEST_H
#define VAJA02_MESSAGE_MOVEMENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vaja02
{
template <class ContainerAllocator>
struct MovementRequest_
{
  typedef MovementRequest_<ContainerAllocator> Type;

  MovementRequest_()
    : move_shape()
    , duration(0)  {
    }
  MovementRequest_(const ContainerAllocator& _alloc)
    : move_shape(_alloc)
    , duration(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _move_shape_type;
  _move_shape_type move_shape;

   typedef int64_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::vaja02::MovementRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vaja02::MovementRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MovementRequest_

typedef ::vaja02::MovementRequest_<std::allocator<void> > MovementRequest;

typedef boost::shared_ptr< ::vaja02::MovementRequest > MovementRequestPtr;
typedef boost::shared_ptr< ::vaja02::MovementRequest const> MovementRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vaja02::MovementRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vaja02::MovementRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vaja02

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vaja02::MovementRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vaja02::MovementRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaja02::MovementRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaja02::MovementRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaja02::MovementRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaja02::MovementRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vaja02::MovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efed902aaa4c34dda361975de64b143e";
  }

  static const char* value(const ::vaja02::MovementRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefed902aaa4c34ddULL;
  static const uint64_t static_value2 = 0xa361975de64b143eULL;
};

template<class ContainerAllocator>
struct DataType< ::vaja02::MovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vaja02/MovementRequest";
  }

  static const char* value(const ::vaja02::MovementRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vaja02::MovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string move_shape\n\
int64 duration\n\
";
  }

  static const char* value(const ::vaja02::MovementRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vaja02::MovementRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.move_shape);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MovementRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vaja02::MovementRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vaja02::MovementRequest_<ContainerAllocator>& v)
  {
    s << indent << "move_shape: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.move_shape);
    s << indent << "duration: ";
    Printer<int64_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VAJA02_MESSAGE_MOVEMENTREQUEST_H
